// Interactive Beef Cuts Data
export const beefCuts = [
  {
    id: "cut_filet",
    number: "5",
    type: "regular",
    name_fr: "Filet de bœuf",
    name_en: "Tenderloin",
    name_ja: "ヒレ",
    points: "55,30 68,30 68,42 55,42",
    properties: { tenderness: "★★★★★", fat: "★☆☆☆☆", collagen: "★☆☆☆☆" },
    cooking: "強火ステーキ、ロースト、短時間ソテー",
    science: "運動量が最も少ない筋肉。結合組織が極少で加熱による硬化が起きにくい。",
    classification: "Steak cut（高級ステーキ部位）",
    logic: "High heat / Short cook",
    chef_note: "火入れの“1分”が品質を決める。"
  },
  {
    id: "cut_rumsteck",
    number: "2",
    type: "regular",
    name_fr: "Rumsteck",
    name_en: "Rump",
    name_ja: "ランプ",
    points: "68,28 78,28 78,42 68,42",
    properties: { tenderness: "★★★★☆", fat: "★★☆☆☆", collagen: "★★☆☆☆" },
    cooking: "ステーキ、ロースト",
    science: "運動はあるが筋繊維が均質で、鉄分と旨味が強い。",
    classification: "Steak cut / Roast cut",
    logic: "High heat / Medium cook",
    chef_note: "「肉汁を噛む」ための部位。"
  },
  {
    id: "cut_aiguillette",
    number: "4",
    type: "regular",
    name_fr: "Aiguillette de rumsteck",
    name_en: "Sirloin cap (Aiguillette de baronne)",
    name_ja: "イチボ",
    points: "72,40 84,40 84,52 72,52",
    properties: { tenderness: "★★★★☆", fat: "★★★☆☆", collagen: "★★☆☆☆" },
    cooking: "ロースト、厚切りステーキ",
    science: "脂層が断熱材として働き、内部の水分保持力が高い。",
    classification: "Roast cut（塊肉向き）",
    logic: "Roast / Medium heat",
    chef_note: "“塊で焼くほど完成度が上がる部位”。"
  },
  {
    id: "cut_palette",
    number: "8",
    type: "regular",
    name_fr: "Dessus de palette",
    name_en: "Chuck flap",
    name_ja: "ザブトン",
    points: "28,26 44,26 44,42 28,42",
    properties: { tenderness: "★★★★☆", fat: "★★★★★", collagen: "★★★☆☆" },
    cooking: "煮込み、低温ロースト",
    science: "脂と筋間コラーゲンが共存。加熱で乳化しソース化する。",
    classification: "Braise cut（煮込み用）",
    logic: "Low heat / Long cook",
    chef_note: "“焼くより溶かす部位”。"
  },
  {
    id: "cut_poitrine",
    number: "13",
    type: "regular",
    name_fr: "Poitrine de bœuf",
    name_en: "Brisket",
    name_ja: "ブリスケ",
    points: "28,45 44,45 44,66 28,66",
    properties: { tenderness: "★★☆☆☆", fat: "★★★★☆", collagen: "★★★★★" },
    cooking: "ポトフ、長時間煮込み",
    science: "支持筋肉構造でコラーゲン密度が高い。低温長時間でゼラチン化。",
    classification: "Braise cut",
    logic: "Low heat / Very long cook",
    chef_note: "“時間が旨味に変わる典型”。"
  },
  {
    id: "cut_langue",
    number: "1",
    type: "offal",
    name_fr: "Langue de bœuf",
    name_en: "Langue de bœuf",
    name_ja: "タン",
    points: "4,30 18,30 18,48 4,48",
    properties: { tenderness: "★★★☆☆（焼き） / ★★★★★（煮込み）", fat: "★★★☆☆", collagen: "★★★★☆" },
    cooking: "煮込み、スライスソテー",
    science: "筋＋結合組織が強く、加熱でゼラチン質化する。",
    classification: "Abats nobles（高級内臓）",
    logic: "Long cook",
    chef_note: "“煮込むほど格が上がる部位”。"
  },
  {
    id: "cut_onglet",
    number: "9",
    type: "offal",
    name_fr: "Onglet",
    name_en: "Skirt / Hanging tender",
    name_ja: "ハラミ",
    points: "48,50 62,50 62,65 48,65",
    properties: { tenderness: "★★★★☆", fat: "★★★☆☆", collagen: "★★☆☆☆" },
    cooking: "ステーキ（レア）",
    science: "横隔膜筋。筋繊維が粗く赤身の旨味が強い。",
    classification: "Boucher cut（肉屋が好む部位）",
    logic: "High heat / Very short cook",
    chef_note: "“焼きすぎると価値が消える”。"
  },
  {
    id: "cut_foie",
    number: "3",
    type: "offal",
    name_fr: "Foie de bœuf",
    name_en: "Liver",
    name_ja: "レバー",
    points: "42,40 56,40 56,52 42,52",
    properties: { tenderness: "★★★★☆", fat: "★★☆☆☆", collagen: "★☆☆☆☆" },
    cooking: "ソテー、パテ",
    science: "実質臓器。加熱でタンパク質凝固が急速に進む。",
    classification: "Abats",
    logic: "Medium heat / Very short cook",
    chef_note: "“数十秒 of 差で別食材”。"
  },
  {
    id: "cut_tripe",
    number: "10",
    type: "offal",
    name_fr: "Tripes",
    name_en: "Honeycomb tripe",
    name_ja: "ハチノス",
    points: "38,54 52,54 52,70 38,70",
    properties: { tenderness: "★☆☆☆☆ → ★★★★★（煮込み）", fat: "★☆☆☆☆", collagen: "★★★★★" },
    cooking: "長時間煮込み",
    science: "蜂 of 巣状コラーゲン構造。酸と時間で分解される。",
    classification: "Abats traditionnels",
    logic: "Very long cook",
    chef_note: "“時間が構造を壊す食材”。"
  },
  {
    id: "cut_boyaux",
    number: "14",
    type: "offal",
    name_fr: "Boyaux",
    name_en: "Intestine",
    name_ja: "腸",
    points: "80,62 94,62 94,78 80,78",
    properties: { tenderness: "★★☆☆☆", fat: "★★★★☆", collagen: "★★★★☆" },
    cooking: "ソーセージ, グリル",
    science: "平滑筋＋脂肪層。発酵・香辛料と相性が良い。",
    classification: "Charcuterie",
    logic: "Medium heat / Processed",
    chef_note: "“単体ではなく構造として使う部位”。"
  }
];

// Interactive Poultry Cuts Data
export const poultryCuts = [
  {
    id: "cut_chicken_breast",
    number: "4",
    type: "regular",
    name_fr: "Blanc de poulet",
    name_en: "Breast",
    name_ja: "むね",
    points: "34,66 46,66 46,82 34,82",
    properties: { tenderness: "★★☆☆☆", fat: "★☆☆☆☆", collagen: "★☆☆☆☆" },
    cooking: "ポシェ、ソテー、低温調理",
    science: "結合組織が少なく、高温で加熱すると水分が抜けやすい。低温でゆっくり火入れするとしっとり仕上がる。",
    classification: "Suprême de volaille",
    logic: "Low temperature / Delicate heat",
    chef_note: "加熱 of 誤差がそのまま品質差になる部位。"
  },
  {
    id: "cut_chicken_tender",
    number: "6",
    type: "regular",
    name_fr: "Aiguillette de poulet",
    name_en: "Tenderloin",
    name_ja: "ささみ",
    points: "38,62 48,62 48,76 38,76",
    properties: { tenderness: "★★★☆☆", fat: "★☆☆☆☆", collagen: "★☆☆☆☆" },
    cooking: "ソテー、パン粉焼き、軽いフリット",
    science: "筋繊維が細く水分保持が弱い。短時間加熱で内部水分を守る必要がある。",
    classification: "Aiguillettes de poulet panées",
    logic: "Short cook / Gentle heat",
    chef_note: "「火を入れる時間」より「火を止める判断」が重要。"
  },
  {
    id: "cut_chicken_thigh",
    number: "3",
    type: "regular",
    name_fr: "Cuisse de poulet",
    name_en: "Thigh",
    name_ja: "もも",
    points: "48,70 62,70 62,86 48,86",
    properties: { tenderness: "★★★★☆", fat: "★★★☆☆", collagen: "★★★☆☆" },
    cooking: "ロティ、ブレゼ、煮込み",
    science: "運動量が多くミオグロビンが豊富。長時間加熱でコラーゲンがゼラチン化し、旨味が増す。",
    classification: "Coq au vin",
    logic: "Long cook / Medium heat",
    chef_note: "火を入れるほど価値が上がる数少ない部位。"
  },
  {
    id: "cut_chicken_shoulder",
    number: "5",
    type: "regular",
    name_fr: "Épaule de poulet",
    name_en: "Shoulder (Furisode)",
    name_ja: "ふりそで",
    points: "36,60 46,60 46,72 36,72",
    properties: { tenderness: "★★★☆☆", fat: "★★☆☆☆", collagen: "★★☆☆☆" },
    cooking: "ソテー、軽い煮込み",
    science: "むねとももの中間的構造。加熱耐性と保水性のバランスが良い。",
    classification: "Sauté de volaille",
    logic: "Medium heat / Balanced cook",
    chef_note: "万能だが「主役より補助」に向く部位。"
  },
  {
    id: "cut_chicken_drumette",
    number: "2",
    type: "regular",
    name_fr: "Pilon de poulet",
    name_en: "Drumette",
    name_ja: "手羽もと",
    points: "44,78 56,78 56,92 44,92",
    properties: { tenderness: "★★★☆☆", fat: "★★★☆☆", collagen: "★★★★☆" },
    cooking: "ロティ、オーブン焼き、グリル",
    science: "骨周辺にコラーゲンが集中。長時間加熱でゼラチン化しジューシーになる。",
    classification: "Pilons rôtis aux épices",
    logic: "Medium-high heat / Bone-in cook",
    chef_note: "骨付き加熱の“旨味の設計図”が最も分かりやすい部位。"
  },
  {
    id: "cut_chicken_wing_joint",
    number: "1",
    type: "regular",
    name_fr: "Aileron de poulet",
    name_en: "Wing mid joint",
    name_ja: "手羽なか",
    points: "42,62 52,62 52,76 42,76",
    properties: { tenderness: "★★★★☆", fat: "★★★★☆", collagen: "★★★★☆" },
    cooking: "コンフィ、低温ロースト",
    science: "皮・脂・コラーゲンの三層構造。低温長時間で完全にゼラチン化する。",
    classification: "Ailerons confits",
    logic: "Low heat / Long cook / Confit",
    chef_note: "「溶ける食感」を作るための部位。"
  },
  {
    id: "cut_chicken_wing",
    number: "1",
    type: "regular",
    name_fr: "Aile de poulet",
    name_en: "Wing",
    name_ja: "手羽先",
    points: "44,64 54,64 54,74 44,74",
    properties: { tenderness: "★★★☆☆", fat: "★★★★☆", collagen: "★★★★★" },
    cooking: "ブイヨン、ロースト、揚げ",
    science: "コラーゲン含有量が極めて高く、加熱でゼラチン化しスープに濃度を与える。",
    classification: "Bouillon de volaille / Fond",
    logic: "Simmer / Long cook",
    chef_note: "フランス料理の“出汁の骨格”になる部位。"
  },
  {
    id: "cut_chicken_skin",
    number: "8",
    type: "regular",
    name_fr: "Peau de poulet",
    name_en: "Skin",
    name_ja: "かわ",
    points: "46,54 56,54 56,66 46,66",
    properties: { tenderness: "★★★☆☆", fat: "★★★★★", collagen: "★★★★★" },
    cooking: "ロースト、テュイル、揚げ焼き",
    science: "加熱により脂が溶け、コラーゲンが乾燥・再構築されクリスピー化する。",
    classification: "Tuile de peau de poulet",
    logic: "High heat / Fat render",
    chef_note: "「脂を抜くと完成する」特殊部位。"
  },
  {
    id: "cut_chicken_heart",
    number: "12",
    type: "offal",
    name_fr: "Cœur de poulet",
    name_en: "Heart",
    name_ja: "ハツ",
    points: "40,74 50,74 50,86 40,86",
    properties: { tenderness: "★★★☆☆", fat: "★★☆☆☆", collagen: "★★☆☆☆" },
    cooking: "グリル、串焼き",
    science: "心筋由来の高密度筋繊維。短時間加熱で弾力を残す。",
    classification: "Brochettes de cœurs de poulet",
    logic: "High heat / Quick cook",
    chef_note: "火を入れすぎると一気に硬化する。"
  },
  {
    id: "cut_chicken_cardiac_base",
    number: "12",
    type: "offal",
    name_fr: "Base de cœur",
    name_en: "Cardiac base",
    name_ja: "ハツモト",
    points: "42,75 52,75 52,85 42,85",
    properties: { tenderness: "★★★★☆", fat: "★★★☆☆", collagen: "★★★☆☆" },
    cooking: "フリカッセ、軽い煮込み",
    science: "血管・弾性繊維構造。クリーム系と相性が良い。",
    classification: "Fricassée d’abats de volaille",
    logic: "Medium heat / Gentle simmer",
    chef_note: "内臓の中でも“ソース適性が高い”部位。"
  },
  {
    id: "cut_chicken_liver",
    number: "13",
    type: "offal",
    name_fr: "Foie de poulet",
    name_en: "Liver",
    name_ja: "レバー",
    points: "38,78 48,78 48,90 38,90",
    properties: { tenderness: "★★★★☆", fat: "★★☆☆☆", collagen: "★☆☆☆☆" },
    cooking: "パテ、ソテー、ムース",
    science: "実質器官で構造が均質。加熱しすぎると急速に水分が抜ける。",
    classification: "Pâté de foies de volaille",
    logic: "Medium heat / Short cook",
    chef_note: "“火入れの1分差”で別食材になる。"
  },
  {
    id: "cut_chicken_gizzard",
    number: "11",
    type: "offal",
    name_fr: "Gésier de poulet",
    name_en: "Gizzard",
    name_ja: "砂肝",
    points: "42,72 52,72 52,82 42,82",
    properties: { tenderness: "★★☆☆☆", fat: "★☆☆☆☆", collagen: "★☆☆☆☆" },
    cooking: "コンフィ、煮込み、サラダ",
    science: "強い筋肉組織。低温長時間で繊維がほぐれる。",
    classification: "Salade Landaise",
    logic: "Low heat / Long cook / Confit",
    chef_note: "“砂肝の噛み応えの設計”を理解する部位。"
  },
  {
    id: "cut_chicken_tail",
    number: "9",
    type: "offal",
    name_fr: "Croupion",
    name_en: "Tail (Bonjiri)",
    name_ja: "ボンジリ",
    points: "50,60 60,60 60,72 50,72",
    properties: { tenderness: "★★★★★", fat: "★★★★★", collagen: "★★★☆☆" },
    cooking: "ロースト、グリル",
    science: "脂肪の集中部位。加熱で純脂の旨味が凝縮する。",
    classification: "Poulet rôti",
    logic: "Medium heat / Crisp grill",
    chef_note: "最も“快楽的な脂”を持つ部位。"
  },
  {
    id: "cut_chicken_cartilage_yagen",
    number: "14",
    type: "offal",
    name_fr: "Cartilage de poulet",
    name_en: "Cartilage (Yagen)",
    name_ja: "ヤゲン軟骨",
    points: "36,78 46,78 46,90 36,90",
    properties: { tenderness: "★☆☆☆☆", fat: "★☆☆☆☆", collagen: "★★★★★" },
    cooking: "スープ、フォン",
    science: "コラーゲンとプロテオグリカンが主体。加熱でゼラチン化しとろみを生む。",
    classification: "Fonds de volaille",
    logic: "Simmer / Long extraction",
    chef_note: "“ソースの粘度を作る素材”。"
  },
  {
    id: "cut_chicken_cartilage_knee",
    number: "15",
    type: "offal",
    name_fr: "Cartilage de poulet",
    name_en: "Cartilage (Nankotsu)",
    name_ja: "ひざ軟骨",
    points: "48,88 58,88 58,98 48,98",
    properties: { tenderness: "★☆☆☆☆", fat: "★☆☆☆☆", collagen: "★★★★★" },
    cooking: "スープ、フォン",
    science: "コラーゲンとプロテオグリカンが主体。加熱でゼラチン化しとろみを生む。",
    classification: "Fonds de volaille",
    logic: "Simmer / Long extraction",
    chef_note: "“ソースの粘度を作る素材”。"
  }
];

// Interactive Pork Cuts Data
export const porcCuts = [
  {
    id: "cut_pork_loin",
    number: "1",
    type: "regular",
    name_fr: "Longe de porc",
    name_en: "Pork Loin",
    name_ja: "ロース",
    points: "52,56 64,56 64,72 52,72",
    properties: { tenderness: "★★★★☆", fat: "★★★☆☆", collagen: "★☆☆☆☆" },
    cooking: "ロースト、ソテー",
    science: "背側筋。均質な筋繊維＋脂の蓋で水分保持。",
    classification: "Roast cut",
    logic: "High heat / Short roast",
    chef_note: "“最も安定したステーキ素材”。"
  },
  {
    id: "cut_pork_tenderloin",
    number: "2",
    type: "regular",
    name_fr: "Filet mignon",
    name_en: "Tenderloin",
    name_ja: "ヒレ",
    points: "54,50 66,50 66,62 54,62",
    properties: { tenderness: "★★★★★", fat: "★☆☆☆☆", collagen: "★☆☆☆☆" },
    cooking: "ソテー、低温ロースト",
    science: "大腰筋。運動ゼロに近く筋繊維が極細。",
    classification: "Premium steak cut",
    logic: "Very short cook / Precision heat",
    chef_note: "“過熱した瞬間に価値が落ちる”。"
  },
  {
    id: "cut_pork_shoulder_loin",
    number: "3",
    type: "regular",
    name_fr: "Échine",
    name_en: "Shoulder loin",
    name_ja: "かたロース",
    points: "36,50 48,50 48,66 36,66",
    properties: { tenderness: "★★★★☆", fat: "★★★★☆", collagen: "★★★☆☆" },
    cooking: "煮込み、ロースト",
    science: "脂と赤身の網構造。熱耐性が高い。",
    classification: "Braise + Roast hybrid",
    logic: "Medium / Long cook対応",
    chef_note: "“焼きと煮込みの中間解”。"
  },
  {
    id: "cut_pork_belly",
    number: "4",
    type: "regular",
    name_fr: "Poitrine de porc",
    name_en: "Belly",
    name_ja: "ばら",
    points: "42,72 56,72 56,86 42,86",
    properties: { tenderness: "★★★★☆", fat: "★★★★★", collagen: "★★★★☆" },
    cooking: "煮込み、塩漬け、ロースト",
    science: "層状脂肪構造。塩で水分活性が下がり熟成が進む。",
    classification: "Charcuterie base cut",
    logic: "Long cook / Cure / Roast",
    chef_note: "“加工前提で完成する部位”。"
  },
  {
    id: "cut_pork_ham",
    number: "5",
    type: "regular",
    name_fr: "Jambon",
    name_en: "Ham leg (Cuissot)",
    name_ja: "もも",
    points: "60,60 74,60 74,78 60,78",
    properties: { tenderness: "★★★☆☆", fat: "★★☆☆☆", collagen: "★★☆☆☆" },
    cooking: "ハム、ロースト",
    science: "大筋肉群。塩分浸透と熟成に最適化。",
    classification: "Charcuterie premium",
    logic: "Cure / Low temp cook",
    chef_note: "“豚の価値はここで決まる”。"
  },
  {
    id: "cut_pork_cheek",
    number: "6",
    type: "offal",
    name_fr: "Joue de porc",
    name_en: "Cheek",
    name_ja: "頬肉",
    points: "28,70 40,70 40,84 28,84",
    properties: { tenderness: "★☆☆☆☆ → ★★★★★", fat: "★★★☆☆", collagen: "★★★★★" },
    cooking: "コンフィ、煮込み",
    science: "咀嚼筋。高密度コラーゲンが長時間で崩壊。",
    classification: "Braise cut (premium offal)",
    logic: "Very long cook",
    chef_note: "“ゼラチン化の完成形”。"
  },
  {
    id: "cut_pork_liver",
    number: "7",
    type: "offal",
    name_fr: "Foie de porc",
    name_en: "Liver",
    name_ja: "レバー",
    points: "46,64 58,64 58,76 46,76",
    properties: { tenderness: "★★★★☆", fat: "★★☆☆☆", collagen: "★☆☆☆☆" },
    cooking: "テリーヌ、パテ",
    science: "実質臓器。酸化が早く乳化処理が重要。",
    classification: "Charcuterie essential",
    logic: "Low heat / Emulsion",
    chef_note: "“単体より構造化して使う”。"
  },
  {
    id: "cut_pork_tongue",
    number: "8",
    type: "offal",
    name_fr: "Langue",
    name_en: "Tongue",
    name_ja: "タン",
    points: "22,70 32,70 32,84 22,84",
    properties: { tenderness: "★★★☆☆ → ★★★★★", fat: "★★★☆☆", collagen: "★★★★☆" },
    cooking: "煮込み、ゼリー寄せ",
    science: "筋＋結合組織の複合体。加熱で一体化する。",
    classification: "Abats nobles",
    logic: "Long cook / Gel setting",
    chef_note: "“煮ると一つの構造になる”。"
  },
  {
    id: "cut_pork_trotter",
    number: "9",
    type: "offal",
    name_fr: "Pied de porc",
    name_en: "Trotter",
    name_ja: "豚足",
    points: "38,88 50,88 50,98 38,98",
    properties: { tenderness: "★☆☆☆☆ → ★★★★★", fat: "★★★☆☆", collagen: "★★★★★" },
    cooking: "煮込み→焼き",
    science: "コラーゲン塊。ゼラチン→再加熱でテクスチャー分離。",
    classification: "Classic peasant cuisine",
    logic: "Very long cook + roast finish",
    chef_note: "“二段階変換で完成する部位”。"
  },
  {
    id: "cut_pork_intestine",
    number: "10",
    type: "offal",
    name_fr: "Boyaux",
    name_en: "Intestine",
    name_ja: "腸",
    points: "50,76 64,76 64,88 50,88",
    properties: { tenderness: "★★☆☆☆", fat: "★★★★☆", collagen: "★★★★☆" },
    cooking: "ソーセージ、加工",
    science: "平滑筋＋脂。香辛料と発酵で価値が決まる。",
    classification: "Charcuterie core material",
    logic: "Processed / Seasoned",
    chef_note: "“単体ではなく設計素材”。"
  }
];

// Interactive Fish Cuts Data
export const fishCuts = [
  {
    id: "cut_kokotxa_de_merlu",
    number: "1",
    type: "regular",
    name_fr: "Kokotxa de merlu",
    name_en: "Hake Kokotxa (jaw meat)",
    name_ja: "ココチャ（メルルーサの顎肉）",
    points: "22,46 36,46 36,58 22,58",
    properties: { tenderness: "★★★★★", fat: "★★☆☆☆", collagen: "★★★★★" },
    cooking: "ピルピル乳化、ポシェ",
    science: "魚の頭部下にある最も動かす筋肉かつゼラチンの宝庫。熱を加えることで豊富な天然コラーゲンが容易に溶け出す。",
    classification: "Spécialité basque (バスク特産高級部位)",
    logic: "Low heat / Emulsification",
    chef_note: "オリーブ油を完全乳化させ、ソースと一体化させる。"
  },
  {
    id: "cut_fish_fillet",
    number: "2",
    type: "regular",
    name_fr: "Filet de poisson",
    name_en: "Fish Fillet",
    name_ja: "フィレ（魚の切り身）",
    points: "44,40 68,40 68,54 44,54",
    properties: { tenderness: "★★★★☆", fat: "★☆☆☆☆", collagen: "★☆☆☆☆" },
    cooking: "ソテー、ポワレ、蒸し",
    science: "赤身および白身の筋肉繊維。陸上動物に比べて結合組織（コラーゲン）が非常に少ないため、短時間の精密な加熱が必須。",
    classification: "Poisson de fond (底生魚・白身)",
    logic: "Short cook / High-precision heat",
    chef_note: "皮はパリッと、身はしっとりと仕上げる。"
  }
];

// Interactive Other Meats Cuts Data
export const otherCuts = [
  {
    id: "cut_magret_de_canard",
    number: "1",
    type: "regular",
    name_fr: "Magret de canard",
    name_en: "Duck breast (Fattened)",
    name_ja: "マグレ・ド・カナール（フォアグラ鴨の胸肉）",
    points: "36,58 52,58 52,74 36,74",
    properties: { tenderness: "★★★★☆", fat: "★★★★★", collagen: "★★☆☆☆" },
    cooking: "ポワレ、ロティ",
    science: "フォアグラ用に肥育された鴨の胸肉。厚い皮下脂肪層を持ち、脂を溶かし出しながらその脂で揚げるように皮目をパリパリに焼く。",
    classification: "Volaille de prestige (高級家禽)",
    logic: "Fat rendering / Medium-rare finish",
    chef_note: "皮目の格子状の切れ込みと、絶え間ないアロゼが成功の鍵。"
  },
  {
    id: "cut_gibier_chevreuil",
    number: "2",
    type: "regular",
    name_fr: "Filet de chevreuil",
    name_en: "Venison loin (Roe deer)",
    name_ja: "ロワイヤル・ド・シュヴルイユ（鹿のロース）",
    points: "54,46 72,46 72,62 54,62",
    properties: { tenderness: "★★★★☆", fat: "★☆☆☆☆", collagen: "★★★☆☆" },
    cooking: "ロティ、ポワレ、ソース・ポワブラード",
    science: "野生の鹿肉。極めて低脂肪で高タンパク質な赤身肉のため、強火での過加熱は禁物。芯温54°C前後を狙う繊細な火入れが必要。",
    classification: "Gibier de poil (毛のある野生獣肉)",
    logic: "Delicate roast / Rare to Medium-rare",
    chef_note: "ベリー系や赤ワインの濃厚な酸味ソースを合わせる。"
  }
];
