// Interactive Vegetables (Légumes) Data
export const vegetableCuts = [
  {
    id: "ing_oignon",
    number: "1",
    name_fr: "Oignon",
    name_en: "Onion",
    name_ja: "オニョン（玉ねぎ）",
    pin: { x: 32, y: 48 },
    properties: { tenderness: "★★★☆☆", fat: "☆☆☆☆☆", collagen: "☆☆☆☆☆" },
    cooking: "シズレ（みじん切り）、スライス、長時間炒めてキャラメリゼ",
    science: "生の玉ねぎには刺激臭成分（アリシンなどの硫黄化合物）が含まれますが、加熱すると熱分解されて甘味成分（プロピルメルプタンなど）に変わり、砂糖の数十倍の甘みを感じるようになります。また、アミノ酸と糖が反応する「メイラード反応」により、ソースの深い褐色（フォン）とコクを作ります。",
    classification: "Garniture aromatique de base",
    logic: "Sueur (sweating) / Maturation / Color base",
    chef_note: "玉ねぎ、人参、セロリを炒めたものは「Mirepoix（ミルポワ）」と呼ばれ、ほぼすべてのフレンチソースの出汁のベースになります。"
  },
  {
    id: "ing_echalote",
    number: "2",
    name_fr: "Échalote",
    name_en: "Shallot",
    name_ja: "エシャロット",
    pin: { x: 45, y: 55 },
    properties: { tenderness: "★★★★☆", fat: "☆☆☆☆☆", collagen: "☆☆☆☆☆" },
    cooking: "シズレ、ソースのベース（ベアルネーズ、ボルドレーズ）",
    science: "玉ねぎよりも水分が少なく、硫黄化合物の質が非常にデリケート。強い熱で焦がすと一気に苦味が出るため、バターで優しく汗をかかせる（Suer）ことで、上品な甘みとニンニクに似た官能的な香りをソースに溶かし込みます。",
    classification: "Garniture aromatique premium",
    logic: "Suer (gentle sweating) / Emulsion aid",
    chef_note: "フランス料理のソースの成否は「シャロットをいかに細かく美しく刻むか（Ciseler）」に掛かっていると言っても過言ではありません。"
  },
  {
    id: "ing_carotte",
    number: "3",
    name_fr: "Carotte",
    name_en: "Carrot",
    name_ja: "キャロット（人参）",
    pin: { x: 58, y: 45 },
    properties: { tenderness: "★★★☆☆", fat: "☆☆☆☆☆", collagen: "☆☆☆☆☆" },
    cooking: "ジュリエンヌ（千切り）、ヴィシー風（輪切りバターグラッセ）",
    science: "オレンジ色の色素は油に溶けやすい「β-カロテン」。バターやバターオイル（Clarified butter）でじっくり炒めることで、色素と香気成分がバターに移り、ソースの仕上がりを鮮やかに美しく引き立てます。また、ペクチンを含み、煮込むことで甘みと適度なとろみを与えます。",
    classification: "Garniture aromatique / Légume d'accompagnement",
    logic: "Sweating in butter / Glace (glazing)",
    chef_note: "「Carottes à la Vichy（人参のヴィシー風）」は、ミネラルウォーター、バター、砂糖で水分がなくなるまで煮詰めて人参自身の糖分で艶（Glace）を出す古典的付け合わせ。"
  },
  {
    id: "ing_poireau",
    number: "4",
    name_fr: "Poireau",
    name_en: "Leek",
    name_ja: "ポワロー（リーキ・西洋ネギ）",
    pin: { x: 25, y: 35 },
    properties: { tenderness: "★★★★☆", fat: "☆☆☆☆☆", collagen: "☆☆☆☆☆" },
    cooking: "ブイヨン用（緑葉部）、バター蒸し煮（白い軟白部）",
    science: "白い茎の部分には可溶性ペクチンと糖質が極めて豊富に含まれており、バターでじっくり低温加熱（Étuver）すると、とろけるような滑らかなテクスチャーに変わり、濃厚な旨味ソースのような役割を果たします。緑の部分はブーケガルニやブイヨンの香りづけに使います。",
    classification: "Garniture aromatique / Bouquet garni core",
    logic: "Étuver (stewing in own juices) / Long simmer",
    chef_note: "じゃがいもとポワローをベースにした冷たいスープ「Vichyssoise（ヴィシソワーズ）」は夏のクラシック。"
  },
  {
    id: "ing_pomme_de_terre",
    number: "5",
    name_fr: "Pomme de terre",
    name_en: "Potato",
    name_ja: "ポム・ド・テール（じゃがいも）",
    pin: { x: 72, y: 55 },
    properties: { tenderness: "★★★☆☆", fat: "☆☆☆☆☆", collagen: "☆☆☆☆☆" },
    cooking: "ピューレ（Purée）、フリット、ポム・デュシェス",
    science: "アミロースとアミロペクチン（澱粉）が主体。茹でて裏ごしし、冷たいバターを大量に練り込むことで、澱粉の粒子を乳化したバターの脂肪分がコーティングし、極めて滑らかでシルキーなピューレが完成します（有名なジョエル・ロブションのレシピ）。過剰に練りすぎると澱粉の粘り（グルテン様）が出てベタつきます。",
    classification: "Féculent（澱粉質食材・主食添え）",
    logic: "Maturation / Starch gelatinization / Butter emulsion",
    chef_note: "裏ごしには必ず「タミ（粉ふるい）」を使い、絶対にブレンダーを使ってはいけません（ベタベタの糊になってしまいます）。"
  },
  {
    id: "ing_celeri",
    number: "6",
    name_fr: "Céleri branche",
    name_en: "Celery stalk",
    name_ja: "セロリ（枝セロリ）",
    pin: { x: 50, y: 32 },
    properties: { tenderness: "★★☆☆☆", fat: "☆☆☆☆☆", collagen: "☆☆☆☆☆" },
    cooking: "ミルポワ（出汁用みじん切り）、ブイヨン",
    science: "アピインなどの独特な揮発性香気成分が豊富。肉のアルカリ性生臭み成分を打ち消すマスキング効果が非常に強く、牛や鶏のフォン（出汁）をとる際には必要不可欠な香気素材です。",
    classification: "Garniture aromatique de base",
    logic: "Masking odor / Simmer extraction",
    chef_note: "強い筋があるため、付け合わせに使う場合はピーラーで表面を厚めに剥き、ブイヨンで柔らかく煮含めます。"
  },
  {
    id: "ing_ail",
    number: "7",
    name_fr: "Ail",
    name_en: "Garlic",
    name_ja: "アイ（にんにく）",
    pin: { x: 42, y: 65 },
    properties: { tenderness: "★★★★★", fat: "☆☆☆☆☆", collagen: "☆☆☆☆☆" },
    cooking: "アシェ（みじん切り）、潰してオイルに香りを移す、丸ごとロースト",
    science: "にんにくの細胞が破壊されると、酵素アリシナーゼが作動して強烈な香り成分アリシンが生成されます。これをオリーブ油などの油脂に移し、ゆっくり加熱することで、香りがオイル全体に拡散し料理のベースを作ります。焦げやすく、焦げると強い苦味が出ます。",
    classification: "Condiment aromatique",
    logic: "Oil infusion / Infimul minimal coloring",
    chef_note: "香りを優しく出したい時は皮付きのまま潰して（Ail en chemise）フライパンに入れ、強く出したい時は芯の芽を除いて微塵切りにします。"
  }
];
